config/routes.rb
Jraff::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts,         only: [:create, :destroy]
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root "static_pages#home"
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/edit',    to: 'users#edit',           via: 'get'

  get '/users' => 'users#home', as: :user_home
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @post = current_user.posts.build if signed_in?
    @feed_items = current_user.feed if signed_in?
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<div class="homepage-user-info">
    <section>
      <h3><%= @current_user.full_name %></h3>
      <h4>@<%= @current_user.username %></h4>
      <%= render 'shared/stats' %>
    </section>
    <%= form_for(@post) do |f| %>
      <div class="field">
        <%= f.text_area :content, placeholder: "Compose new post..." %>
      </div>
      <%= f.submit "Post", class: "homepage-submit" %>
    <% end %>
  </div>

  <div class="user-posts">
    <h3>Posts</h3>
        <%= render 'shared/feed' %>
  </div>



<% else %>
<div class="signin-welcome-message">
<h2>Welcome.</h2>
    <%= form_for(:session, url: sessions_path) do |f| %>

    
    <%= f.text_field :username, placeholder: "Username" %>

    <%= f.password_field :password, placeholder: "Password", class: "signin-password" %>

    <%= f.submit "GO", class: "signin-submit" %>
  <% end %>

  <div class="signin-registermsg">Don't have an account yet? <%= link_to "Register!", signup_path, class: "signup-button" %></div>
</div>


<% end %>