config/routes.rb
Jraff::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts,         only: [:create, :destroy]
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root "static_pages#home"
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/edit',    to: 'users#edit',           via: 'get'

  get '/users' => 'users#home', as: :user_home
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>

      <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,300' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Muli:300,400,300italic,400italic' rel='stylesheet' type='text/css'>

  </head>
  <body>

    <header>
      <div class="persistent-header"> <!-- make the header a separate partial -->
        <h1>jraff<span>.es</span></h1>
        <nav>
          <ul>
            <% if signed_in? %>
              <li><%= link_to "Home", root_url %></li>
              <li><%= link_to current_user.full_name.split(" ").first, current_user %></li>
              <li><%= link_to "Account", '#' %></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            <% else %>
              <li><%= link_to  "Home",    root_url %></li>
              <li><%= link_to  "About",   about_path %></li>
              <li><%= link_to  "Help",    help_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    
    
      <% if !signed_in? && current_page?(root_url) %>
        <div class="container-unsigned"><div class="home-not-signed-in"><%= yield %></div></div>
      <% else %>
        <div class="container"><div class="wrapper"><%= yield %></div>
      <% end %>
      
    </div>

  </body>
</html>